//! /*% device_name_lower %*/.rs
//!
//! autogenerated /*% device_name %*/ peripheral models
//! 
//! NOTICE: GENERATED MODELS ARE INCOMPLETE
//! Read/write and other stateful behavior must be manually implemented.
//! 

/*! peripheral_mods --->
pub mod %peripheral_mod%;
!*/