//! /*{ device_name.lower() }*/.rs
//!
//! autogenerated /*{ device_name }*/ peripheral models
//! 
//! NOTICE: GENERATED MODELS ARE INCOMPLETE
//! Read/write and other stateful behavior must be manually implemented.
//! 

/*% for peripheral_mod in peripheral_mods -%*/
pub mod /*{ peripheral_mod }*/;
/*% endfor %*/
