//! nrf52840.rs
//!
//! autogenerated nrf52840 peripheral models
//! 
//! NOTICE: GENERATED MODELS ARE INCOMPLETE
//! Read/write and other stateful behavior must be manually implemented.
//! 

pub mod ficr;
pub mod uicr;
pub mod gpio;
pub mod gpiote;
pub mod uarte;
pub mod clock;
